// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/usecase/init.go

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"

	models "github.com/backendmagang/project-1/models"
	entity "github.com/backendmagang/project-1/models/entity"
	gomock "github.com/golang/mock/gomock"
)

// MockUsecaseHandler is a mock of UsecaseHandler interface.
type MockUsecaseHandler struct {
	ctrl     *gomock.Controller
	recorder *MockUsecaseHandlerMockRecorder
}

// MockUsecaseHandlerMockRecorder is the mock recorder for MockUsecaseHandler.
type MockUsecaseHandlerMockRecorder struct {
	mock *MockUsecaseHandler
}

// NewMockUsecaseHandler creates a new mock instance.
func NewMockUsecaseHandler(ctrl *gomock.Controller) *MockUsecaseHandler {
	mock := &MockUsecaseHandler{ctrl: ctrl}
	mock.recorder = &MockUsecaseHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsecaseHandler) EXPECT() *MockUsecaseHandlerMockRecorder {
	return m.recorder
}

// DeleteArticle mocks base method.
func (m *MockUsecaseHandler) DeleteArticle(ctx context.Context, req entity.DeleteArticleRequest) models.StandardResponseReq {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteArticle", ctx, req)
	ret0, _ := ret[0].(models.StandardResponseReq)
	return ret0
}

// DeleteArticle indicates an expected call of DeleteArticle.
func (mr *MockUsecaseHandlerMockRecorder) DeleteArticle(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteArticle", reflect.TypeOf((*MockUsecaseHandler)(nil).DeleteArticle), ctx, req)
}

// DeleteCategory mocks base method.
func (m *MockUsecaseHandler) DeleteCategory(ctx context.Context, req entity.DeleteCategoryRequest) models.StandardResponseReq {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCategory", ctx, req)
	ret0, _ := ret[0].(models.StandardResponseReq)
	return ret0
}

// DeleteCategory indicates an expected call of DeleteCategory.
func (mr *MockUsecaseHandlerMockRecorder) DeleteCategory(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCategory", reflect.TypeOf((*MockUsecaseHandler)(nil).DeleteCategory), ctx, req)
}

// GetArticleDetails mocks base method.
func (m *MockUsecaseHandler) GetArticleDetails(ctx context.Context, req entity.GetArticleDetailsRequest) models.StandardResponseReq {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetArticleDetails", ctx, req)
	ret0, _ := ret[0].(models.StandardResponseReq)
	return ret0
}

// GetArticleDetails indicates an expected call of GetArticleDetails.
func (mr *MockUsecaseHandlerMockRecorder) GetArticleDetails(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArticleDetails", reflect.TypeOf((*MockUsecaseHandler)(nil).GetArticleDetails), ctx, req)
}

// GetArticles mocks base method.
func (m *MockUsecaseHandler) GetArticles(ctx context.Context, req entity.GetArticlesRequest) models.StandardResponseReq {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetArticles", ctx, req)
	ret0, _ := ret[0].(models.StandardResponseReq)
	return ret0
}

// GetArticles indicates an expected call of GetArticles.
func (mr *MockUsecaseHandlerMockRecorder) GetArticles(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArticles", reflect.TypeOf((*MockUsecaseHandler)(nil).GetArticles), ctx, req)
}

// GetCategoryDetails mocks base method.
func (m *MockUsecaseHandler) GetCategoryDetails(ctx context.Context, req entity.GetCategoryDetailsRequest) models.StandardResponseReq {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCategoryDetails", ctx, req)
	ret0, _ := ret[0].(models.StandardResponseReq)
	return ret0
}

// GetCategoryDetails indicates an expected call of GetCategoryDetails.
func (mr *MockUsecaseHandlerMockRecorder) GetCategoryDetails(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCategoryDetails", reflect.TypeOf((*MockUsecaseHandler)(nil).GetCategoryDetails), ctx, req)
}

// GetCategoryTree mocks base method.
func (m *MockUsecaseHandler) GetCategoryTree(ctx context.Context, req entity.GetCategoriesRequest) models.StandardResponseReq {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCategoryTree", ctx, req)
	ret0, _ := ret[0].(models.StandardResponseReq)
	return ret0
}

// GetCategoryTree indicates an expected call of GetCategoryTree.
func (mr *MockUsecaseHandlerMockRecorder) GetCategoryTree(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCategoryTree", reflect.TypeOf((*MockUsecaseHandler)(nil).GetCategoryTree), ctx, req)
}

// InsertArticle mocks base method.
func (m *MockUsecaseHandler) InsertArticle(ctx context.Context, req entity.InsertArticleRequest) models.StandardResponseReq {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertArticle", ctx, req)
	ret0, _ := ret[0].(models.StandardResponseReq)
	return ret0
}

// InsertArticle indicates an expected call of InsertArticle.
func (mr *MockUsecaseHandlerMockRecorder) InsertArticle(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertArticle", reflect.TypeOf((*MockUsecaseHandler)(nil).InsertArticle), ctx, req)
}

// InsertCategory mocks base method.
func (m *MockUsecaseHandler) InsertCategory(ctx context.Context, req entity.InsertCategoryRequest) models.StandardResponseReq {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertCategory", ctx, req)
	ret0, _ := ret[0].(models.StandardResponseReq)
	return ret0
}

// InsertCategory indicates an expected call of InsertCategory.
func (mr *MockUsecaseHandlerMockRecorder) InsertCategory(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertCategory", reflect.TypeOf((*MockUsecaseHandler)(nil).InsertCategory), ctx, req)
}

// UpdateArticle mocks base method.
func (m *MockUsecaseHandler) UpdateArticle(ctx context.Context, req entity.UpdateArticleRequest) models.StandardResponseReq {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateArticle", ctx, req)
	ret0, _ := ret[0].(models.StandardResponseReq)
	return ret0
}

// UpdateArticle indicates an expected call of UpdateArticle.
func (mr *MockUsecaseHandlerMockRecorder) UpdateArticle(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateArticle", reflect.TypeOf((*MockUsecaseHandler)(nil).UpdateArticle), ctx, req)
}

// UpdateCategory mocks base method.
func (m *MockUsecaseHandler) UpdateCategory(ctx context.Context, req entity.UpdateCategoryRequest) models.StandardResponseReq {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCategory", ctx, req)
	ret0, _ := ret[0].(models.StandardResponseReq)
	return ret0
}

// UpdateCategory indicates an expected call of UpdateCategory.
func (mr *MockUsecaseHandlerMockRecorder) UpdateCategory(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCategory", reflect.TypeOf((*MockUsecaseHandler)(nil).UpdateCategory), ctx, req)
}
