// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/repository/postgres/init.go

// Package mock_postgres is a generated GoMock package.
package mock_postgres

import (
	context "context"
	reflect "reflect"

	entity "github.com/backendmagang/project-1/models/entity"
	gomock "github.com/golang/mock/gomock"
)

// MockRepositoryHandler is a mock of RepositoryHandler interface.
type MockRepositoryHandler struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryHandlerMockRecorder
}

// MockRepositoryHandlerMockRecorder is the mock recorder for MockRepositoryHandler.
type MockRepositoryHandlerMockRecorder struct {
	mock *MockRepositoryHandler
}

// NewMockRepositoryHandler creates a new mock instance.
func NewMockRepositoryHandler(ctrl *gomock.Controller) *MockRepositoryHandler {
	mock := &MockRepositoryHandler{ctrl: ctrl}
	mock.recorder = &MockRepositoryHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepositoryHandler) EXPECT() *MockRepositoryHandlerMockRecorder {
	return m.recorder
}

// DeleteArticle mocks base method.
func (m *MockRepositoryHandler) DeleteArticle(ctx context.Context, req entity.DeleteArticleRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteArticle", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteArticle indicates an expected call of DeleteArticle.
func (mr *MockRepositoryHandlerMockRecorder) DeleteArticle(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteArticle", reflect.TypeOf((*MockRepositoryHandler)(nil).DeleteArticle), ctx, req)
}

// DeleteCategory mocks base method.
func (m *MockRepositoryHandler) DeleteCategory(ctx context.Context, req entity.DeleteCategoryRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCategory", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCategory indicates an expected call of DeleteCategory.
func (mr *MockRepositoryHandlerMockRecorder) DeleteCategory(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCategory", reflect.TypeOf((*MockRepositoryHandler)(nil).DeleteCategory), ctx, req)
}

// GetArticleDetails mocks base method.
func (m *MockRepositoryHandler) GetArticleDetails(ctx context.Context, req entity.GetArticleDetailsRequest) (entity.ArticleResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetArticleDetails", ctx, req)
	ret0, _ := ret[0].(entity.ArticleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetArticleDetails indicates an expected call of GetArticleDetails.
func (mr *MockRepositoryHandlerMockRecorder) GetArticleDetails(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArticleDetails", reflect.TypeOf((*MockRepositoryHandler)(nil).GetArticleDetails), ctx, req)
}

// GetArticles mocks base method.
func (m *MockRepositoryHandler) GetArticles(ctx context.Context, req entity.GetArticlesRequest) ([]entity.ArticleResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetArticles", ctx, req)
	ret0, _ := ret[0].([]entity.ArticleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetArticles indicates an expected call of GetArticles.
func (mr *MockRepositoryHandlerMockRecorder) GetArticles(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArticles", reflect.TypeOf((*MockRepositoryHandler)(nil).GetArticles), ctx, req)
}

// GetCategoryDetails mocks base method.
func (m *MockRepositoryHandler) GetCategoryDetails(ctx context.Context, req entity.GetCategoryDetailsRequest) (entity.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCategoryDetails", ctx, req)
	ret0, _ := ret[0].(entity.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCategoryDetails indicates an expected call of GetCategoryDetails.
func (mr *MockRepositoryHandlerMockRecorder) GetCategoryDetails(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCategoryDetails", reflect.TypeOf((*MockRepositoryHandler)(nil).GetCategoryDetails), ctx, req)
}

// GetCategoryTree mocks base method.
func (m *MockRepositoryHandler) GetCategoryTree(ctx context.Context, req entity.GetCategoriesRequest) ([]entity.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCategoryTree", ctx, req)
	ret0, _ := ret[0].([]entity.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCategoryTree indicates an expected call of GetCategoryTree.
func (mr *MockRepositoryHandlerMockRecorder) GetCategoryTree(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCategoryTree", reflect.TypeOf((*MockRepositoryHandler)(nil).GetCategoryTree), ctx, req)
}

// InsertArticle mocks base method.
func (m *MockRepositoryHandler) InsertArticle(ctx context.Context, article entity.InsertArticleRequest) (entity.ArticleResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertArticle", ctx, article)
	ret0, _ := ret[0].(entity.ArticleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertArticle indicates an expected call of InsertArticle.
func (mr *MockRepositoryHandlerMockRecorder) InsertArticle(ctx, article interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertArticle", reflect.TypeOf((*MockRepositoryHandler)(nil).InsertArticle), ctx, article)
}

// InsertCategory mocks base method.
func (m *MockRepositoryHandler) InsertCategory(ctx context.Context, category entity.InsertCategoryRequest) (entity.InsertCategoryRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertCategory", ctx, category)
	ret0, _ := ret[0].(entity.InsertCategoryRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertCategory indicates an expected call of InsertCategory.
func (mr *MockRepositoryHandlerMockRecorder) InsertCategory(ctx, category interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertCategory", reflect.TypeOf((*MockRepositoryHandler)(nil).InsertCategory), ctx, category)
}

// UpdateArticle mocks base method.
func (m *MockRepositoryHandler) UpdateArticle(ctx context.Context, article entity.UpdateArticleRequest) (entity.ArticleResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateArticle", ctx, article)
	ret0, _ := ret[0].(entity.ArticleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateArticle indicates an expected call of UpdateArticle.
func (mr *MockRepositoryHandlerMockRecorder) UpdateArticle(ctx, article interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateArticle", reflect.TypeOf((*MockRepositoryHandler)(nil).UpdateArticle), ctx, article)
}

// UpdateCategory mocks base method.
func (m *MockRepositoryHandler) UpdateCategory(ctx context.Context, category entity.UpdateCategoryRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCategory", ctx, category)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCategory indicates an expected call of UpdateCategory.
func (mr *MockRepositoryHandlerMockRecorder) UpdateCategory(ctx, category interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCategory", reflect.TypeOf((*MockRepositoryHandler)(nil).UpdateCategory), ctx, category)
}
